[2024-07-31T15:33:25.490+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-30T06:30:00+00:00 [queued]>
[2024-07-31T15:33:25.573+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-30T06:30:00+00:00 [queued]>
[2024-07-31T15:33:25.580+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-07-31T15:33:25.582+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 7
[2024-07-31T15:33:25.583+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-07-31T15:33:25.723+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): FetchFromPostgresql> on 2024-07-30 06:30:00+00:00
[2024-07-31T15:33:25.786+0000] {standard_task_runner.py:52} INFO - Started process 320 to run task
[2024-07-31T15:33:25.797+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Pipeline_', 'FetchFromPostgresql', 'scheduled__2024-07-30T06:30:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_ETL_dataRaw_to_dataClean.py', '--cfg-path', '/tmp/tmp38y6s573', '--error-file', '/tmp/tmpd1rap7j_']
[2024-07-31T15:33:25.809+0000] {standard_task_runner.py:80} INFO - Job 12: Subtask FetchFromPostgresql
[2024-07-31T15:33:27.087+0000] {task_command.py:371} INFO - Running <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-30T06:30:00+00:00 [running]> on host 44d2c61df54a
[2024-07-31T15:33:28.658+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yudis_aditya2
AIRFLOW_CTX_DAG_ID=Pipeline_
AIRFLOW_CTX_TASK_ID=FetchFromPostgresql
AIRFLOW_CTX_EXECUTION_DATE=2024-07-30T06:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-30T06:30:00+00:00
[2024-07-31T15:33:29.284+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: relation "discussion" does not exist
LINE 1: select * from discussion
                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_ETL_dataRaw_to_dataClean.py", line 64, in fetch_from_postgresql
    df= pd.read_sql("select * from discussion",conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 608, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2068, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from discussion': relation "discussion" does not exist
LINE 1: select * from discussion
                      ^

[2024-07-31T15:33:29.820+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline_, task_id=FetchFromPostgresql, execution_date=20240730T063000, start_date=20240731T153325, end_date=20240731T153329
[2024-07-31T15:33:29.936+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task FetchFromPostgresql (Execution failed on sql 'select * from discussion': relation "discussion" does not exist
LINE 1: select * from discussion
                      ^
; 320)
[2024-07-31T15:33:30.035+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-31T15:33:30.391+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
