[2024-07-31T15:34:27.787+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-26T06:30:00+00:00 [queued]>
[2024-07-31T15:34:27.822+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-26T06:30:00+00:00 [queued]>
[2024-07-31T15:34:27.824+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2024-07-31T15:34:27.825+0000] {taskinstance.py:1369} INFO - Starting attempt 3 of 7
[2024-07-31T15:34:27.830+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2024-07-31T15:34:27.906+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): FetchFromPostgresql> on 2024-07-26 06:30:00+00:00
[2024-07-31T15:34:27.935+0000] {standard_task_runner.py:52} INFO - Started process 396 to run task
[2024-07-31T15:34:27.958+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Pipeline_', 'FetchFromPostgresql', 'scheduled__2024-07-26T06:30:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_ETL_dataRaw_to_dataClean.py', '--cfg-path', '/tmp/tmptz2h5l0e', '--error-file', '/tmp/tmps1qom2rk']
[2024-07-31T15:34:27.962+0000] {standard_task_runner.py:80} INFO - Job 25: Subtask FetchFromPostgresql
[2024-07-31T15:34:28.433+0000] {task_command.py:371} INFO - Running <TaskInstance: Pipeline_.FetchFromPostgresql scheduled__2024-07-26T06:30:00+00:00 [running]> on host 44d2c61df54a
[2024-07-31T15:34:28.985+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yudis_aditya2
AIRFLOW_CTX_DAG_ID=Pipeline_
AIRFLOW_CTX_TASK_ID=FetchFromPostgresql
AIRFLOW_CTX_EXECUTION_DATE=2024-07-26T06:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-26T06:30:00+00:00
[2024-07-31T15:34:29.036+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2056, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: relation "discussion" does not exist
LINE 1: select * from discussion
                      ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_ETL_dataRaw_to_dataClean.py", line 64, in fetch_from_postgresql
    df= pd.read_sql("select * from discussion",conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 608, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2116, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 2068, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from discussion': relation "discussion" does not exist
LINE 1: select * from discussion
                      ^

[2024-07-31T15:34:29.074+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline_, task_id=FetchFromPostgresql, execution_date=20240726T063000, start_date=20240731T153427, end_date=20240731T153429
[2024-07-31T15:34:29.114+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task FetchFromPostgresql (Execution failed on sql 'select * from discussion': relation "discussion" does not exist
LINE 1: select * from discussion
                      ^
; 396)
[2024-07-31T15:34:29.152+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-07-31T15:34:29.498+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
